### ISSUE TITLE
Create user API

### ISSUE THREAD

**Issue by nadianeyl** [nadiannis/recipe-app-api#1]
## Tasks

- [x] Implement user registration.
- [x] Implement user login.
- [x] Implement update profile.
- [x] Implement view profile.
